import defaultTheme from 'tailwindcss/defaultTheme';
import forms from '@tailwindcss/forms';
import typography from '@tailwindcss/typography';

/** @type {import('tailwindcss').Config} */
export default {
    content: [
        './vendor/laravel/framework/src/Illuminate/Pagination/resources/views/*.blade.php',
        './vendor/laravel/jetstream/**/*.blade.php',
        './storage/framework/views/*.php',
        './resources/views/**/*.blade.php',
        './resources/js/**/*.vue',
    ],

    theme: {
        extend: {
            colors: {
                'tertiary-fixed-dim': '#c1c7d0',
                'on-secondary-container': '#5c2000',
                'on-surface': '#1a1c1c',
                'on-tertiary-fixed': '#161c23',
                'terracotta-accent': '#D35400',
                'secondary-fixed-dim': '#ffb595',
                'on-primary-container': '#8596ae',
                'secondary-fixed': '#ffdbcd',
                'surface-container': '#eeeeee',
                'outline-variant': '#c4c6cd',
                'surface-container-lowest': '#ffffff',
                'on-primary-fixed-variant': '#38485d',
                'surface-bright': '#f9f9f9',
                'surface-dim': '#dadada',
                'inverse-on-surface': '#f0f1f1',
                'on-surface-variant': '#44474c',
                'on-primary-fixed': '#0b1c30',
                'on-secondary-fixed': '#351000',
                'tertiary-container': '#282e35',
                'inverse-primary': '#b7c8e1',
                'primary-container': '#1e2e42',
                'inverse-surface': '#2f3131',
                background: '#f9f9f9',
                'on-tertiary-fixed-variant': '#41474f',
                'on-error-container': '#93000a',
                secondary: '#a23f00',
                'tertiary-fixed': '#dee3ed',
                'deep-navy': '#1E2E42',
                'slate-text': '#4A5568',
                error: '#ba1a1a',
                'on-error': '#ffffff',
                'primary-fixed': '#d3e4fe',
                'error-container': '#ffdad6',
                'on-secondary': '#ffffff',
                'secondary-container': '#fc7127',
                'on-background': '#1a1c1c',
                surface: '#f9f9f9',
                outline: '#74777d',
                'on-primary': '#ffffff',
                tertiary: '#141920',
                'on-secondary-fixed-variant': '#7c2e00',
                'surface-variant': '#e2e2e2',
                'surface-container-highest': '#e2e2e2',
                'primary-fixed-dim': '#b7c8e1',
                'surface-tint': '#505f76',
                'surface-container-low': '#f3f3f4',
                'on-tertiary': '#ffffff',
                'on-tertiary-container': '#90959e',
                'surface-container-high': '#e8e8e8',
                primary: '#08192c',
                'soft-blue-gray': '#E8EDF7',
            },
            borderRadius: {
                DEFAULT: '0.25rem',
                lg: '0.5rem',
                xl: '0.75rem',
                full: '9999px',
            },
            spacing: {
                unit: '8px',
                'container-max-width': '1280px',
                gutter: '24px',
                'stack-md': '16px',
                'stack-lg': '32px',
                'margin-desktop': '64px',
                'margin-mobile': '16px',
                'stack-sm': '8px',
            },
            fontFamily: {
                sans: ['Source Sans 3', ...defaultTheme.fontFamily.sans],
                'body-md': ['Source Sans 3', ...defaultTheme.fontFamily.sans],
                'headline-md': ['Hanken Grotesk', ...defaultTheme.fontFamily.sans],
                'label-lg': ['Hanken Grotesk', ...defaultTheme.fontFamily.sans],
                'headline-lg-mobile': ['Hanken Grotesk', ...defaultTheme.fontFamily.sans],
                'display-lg': ['Hanken Grotesk', ...defaultTheme.fontFamily.sans],
                'body-lg': ['Source Sans 3', ...defaultTheme.fontFamily.sans],
                'label-md': ['Hanken Grotesk', ...defaultTheme.fontFamily.sans],
                'headline-lg': ['Hanken Grotesk', ...defaultTheme.fontFamily.sans],
            },
            fontSize: {
                'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
                'headline-md': ['24px', { lineHeight: '32px', fontWeight: '600' }],
                'label-lg': ['14px', { lineHeight: '20px', letterSpacing: '0.05em', fontWeight: '600' }],
                'headline-lg-mobile': ['24px', { lineHeight: '32px', fontWeight: '600' }],
                'display-lg': ['48px', { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '700' }],
                'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
                'label-md': ['12px', { lineHeight: '16px', fontWeight: '500' }],
                'headline-lg': ['32px', { lineHeight: '40px', fontWeight: '600' }],
            },
            boxShadow: {
                ambient: '0px 8px 24px rgba(30, 46, 66, 0.05)',
            },
        },
    },

    plugins: [forms, typography],
};
